### ISSUE TITLE
Adjust get job status http return values

### ISSUE THREAD

**Issue by drummerwolli** [zalando-incubator/spark-appliance#39]
https://github.com/zalando/spark-appliance/blob/master/webapp.py#L126-L136

This is wrong in terms of http codes and return values. as long as the job exists and we successfully return something (either an error of the job, or succesfull) we return a 200, if not a 404.

two tasks here:
- return something more programmatic in json format
- adjust error codes

between those two we need some time to adapt the workflows.

**Comment by chutium** [comment]
great, @toarndt finally we have a json return value from the rest api call : ) we can think about handle the json response instead of http return code in our workflows

**Comment by drummerwolli** [comment]
merge this asap as you got the workflows adapted.

**Comment by drummerwolli** [comment]
done with #41
